version: 0.2

env:
  variables:
    APP_TYPE: "dotnet_core_cdk"
    BUILD_TYPE: "full"
    BUILD_PACK: "dotnet_ecs_fargate"
    APP_CSPROJ_LOC: "aspnetapp"
    DOCKER_FILE_PATH: "Dockerfile"
    EKS_CLUSTER_NAME: "windows-prod"
    K8S_FILE_PATH: "devops-automation/eks.yaml"
    K8S_REGION: "us-west-2"
    K8S_NAMESPACE: "application"
    CDK_APP_NAME: "app-cc-dotnet-core-web-docker-master"
    #PIPELINE_OVERRIDE: "devops-automation/pipeline-stages.yml"
    #  ORBITER_PATH: ""
    #  ORBITER_GIT_URL: ""
  #parameter-store:
     # key: "value"
     # key: "value"
  # secrets-manager:
    #  ORBITER_GIT_URL: secret-id:json-key:version-stage:version-id
    #  key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable    
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      docker: 18
      dotnet: 3.0
      nodejs: 10
      python: 3.8  
    commands:
     - wget -O - https://raw.githubusercontent.com/vijayashankar-g/aws-code-pipeline-install-scripts/master/linux/orbiter-install.sh | bash
  build:
    commands:
      - pwd; echo "path of the pipeline $ORBITER_PATH"; cd $ORBITER_PATH
      - python start_build.py
