apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-core
spec:
  selector:
    matchLabels:
      app: dotnet-core
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnet-core
        tier: backend
        track: stable
    spec:
      containers:
      - name: dotnet-core
        image: auto-replace-image
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: Always
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-core-service
  namespace: application
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dotnet-core
    tier: backend
    track: stable
  sessionAffinity: None
  type: LoadBalancer